### ISSUE TITLE
多個 aplayer tag 只會顯示一個、重複 load APlayer 庫

### ISSUE THREAD

**Issue by MeteorVE** [MonoLogueChi/hexo-tag-mmedia#6]
如題
多個 aplayer 的話只會顯示一個
原因估計是使用了 getElementById，所以永遠都會覆蓋掉第一個 div 那邊

舉例 : 
一篇文章內容

```
歌曲1
{% aplayer "Caffeine" "Jeff Williams" "caffeine.mp3" "picture.jpg" "lrc:caffeine.txt" %}

歌曲2
{% aplayer "Caffeine" "Jeff Williams" "caffeine.mp3" "picture.jpg" "lrc:caffeine.txt" %}
```

這樣就只會有一個顯示。

另外，如果放入多個 aplayer tag，每一個都會 load 一次   APlayer 庫 (CSS 和 JS 的)
最簡單查看的方式是打開 console，就會發現 APlayer  Logo 跳了很多次 ... 
對效能有沒有影響不太確定，但有點多餘

**Comment by MonoLogueChi** [comment]
下個版本解決，已有思路
